### ISSUE TITLE
Query newly created object in createGravatar resolver

### ISSUE THREAD

**Issue by namesty** [dOrgTech/the-graph-mutations-spec#41]
When optimistically updating the createGravatar mutation, the "update" parameter passed to Apollo React hook's mutation options is a function. Inside this function the cache is handled directly through a proxy object. Following the exact same pattern works for every mutation execept the createGravatar.

The Proxy.writeQuery function call inside the update function results in the following bug: in the resolver execution, after the gravatar has been created, the queryGravatar function is called and it queries the graph-node with the Apollo client passed through context: this query results in an object with data = null and stale = true.

This commonly happens when the data that the query fetches comes in bad shape (missing a parameter or a wrong data type, for example) but if this exact same query is done externally at the same time it returns the correct result. And after checking the cache, the newly created gravatar has the same shape as the others, so writing it directly should not cause this issue, but it does.

**Comment by dOrgJelli** [comment]
I was able to fix this:
- Clearing Docker's cached data at `./example/subgraph/data`
- If the `getGravatars` query in the resolvers doesn't return something, we loop and wait (10 seconds max) until we get a result
